// Complete NEXUS COLLABS services catalog
// Shared across Services page, Home page, Client form, and Skill selector

export interface ServiceItem {
  name: string;
  desc: string;
}

export interface ServiceCategory {
  id: string;
  title: string;
  icon: string; // Lucide icon name
  color: string;
  skills: ServiceItem[];
}

export const serviceCategories: ServiceCategory[] = [
  {
    id: "dev",
    title: "Web & App Development",
    icon: "Code2",
    color: "#3b82f6",
    skills: [
      { name: "Web Development", desc: "Full-stack websites & web applications" },
      { name: "App Development", desc: "Native & cross-platform mobile apps" },
      { name: "SaaS Development", desc: "Cloud-based software products" },
      { name: "Game Development", desc: "Unity & Unreal engine games" },
      { name: "AR/VR Development", desc: "Immersive reality experiences" },
      { name: "API Integration", desc: "Third-party API development" },
      { name: "WordPress Development", desc: "Custom WordPress solutions" },
      { name: "WordPress Customization", desc: "Theme & plugin customization" },
      { name: "Shopify Development", desc: "E-commerce store building" },
      { name: "Shopify Store Setup", desc: "Complete Shopify deployment" },
      { name: "Shopify App Development", desc: "Custom Shopify apps" },
      { name: "WooCommerce Development", desc: "WooCommerce integration" },
      { name: "Laravel Development", desc: "PHP Laravel applications" },
      { name: "Django Development", desc: "Python Django web apps" },
      { name: "Flask Development", desc: "Python Flask microservices" },
      { name: "Node.js Development", desc: "Server-side JavaScript" },
      { name: "React Development", desc: "React web applications" },
      { name: "Angular Development", desc: "Angular enterprise apps" },
      { name: "Vue.js Development", desc: "Vue.js applications" },
      { name: "Python Programming", desc: "Python application development" },
      { name: "Java Programming", desc: "Java enterprise solutions" },
      { name: "C++ Programming", desc: "C++ software development" },
      { name: "PHP Development", desc: "PHP web development" },
      { name: "Backend API Development", desc: "RESTful & GraphQL APIs" },
      { name: "Landing Page Design", desc: "High-converting landing pages" },
      { name: "E-commerce Development", desc: "Online store development" },
      { name: "Membership Website Setup", desc: "Subscription-based sites" },
      { name: "Blog Website Development", desc: "Professional blog creation" },
      { name: "Portfolio Website Development", desc: "Creative portfolio sites" },
      { name: "Forum Website Development", desc: "Community forum platforms" },
      { name: "News Website Development", desc: "News & media platforms" },
      { name: "Custom CMS Development", desc: "Content management systems" },
      { name: "Android App Development", desc: "Android native apps" },
      { name: "iOS App Development", desc: "iPhone & iPad applications" },
      { name: "Mobile App Design", desc: "Mobile UI/UX design" },
      { name: "Smartwatch App Development", desc: "Wearable applications" },
      { name: "Apple Watch App Development", desc: "watchOS applications" },
      { name: "Android Wear App Development", desc: "Wear OS applications" },
      { name: "Browser Extension Development", desc: "Chrome & Firefox extensions" },
      { name: "Chrome Extension Development", desc: "Chrome Web Store extensions" },
      { name: "Firefox Extension Development", desc: "Firefox add-ons" },
      { name: "WordPress Plugin Development", desc: "Custom WP plugins" },
      { name: "Whiteboard Animation", desc: "Engaging explainer animations" },
    ],
  },
  {
    id: "design",
    title: "Design & Creative",
    icon: "Palette",
    color: "#22d3ee",
    skills: [
      { name: "Graphic Design", desc: "Visual identity & branding" },
      { name: "UI/UX Design", desc: "User interfaces & experiences" },
      { name: "Logo Design", desc: "Brand identity marks" },
      { name: "Motion Graphics", desc: "Animated visual content" },
      { name: "Video Editing", desc: "Post-production & editing" },
      { name: "Photography", desc: "Product & portrait shots" },
      { name: "3D Modeling", desc: "3D asset creation" },
      { name: "NFT Design", desc: "Digital art & collectibles" },
      { name: "Brand Identity", desc: "Complete brand systems" },
      { name: "Branding", desc: "Brand strategy & design" },
      { name: "Packaging Design", desc: "Product packaging visuals" },
      { name: "Business Card Design", desc: "Professional card design" },
      { name: "Brochure Design", desc: "Marketing brochure creation" },
      { name: "Flyer Design", desc: "Promotional flyer design" },
      { name: "Poster Design", desc: "Event & product posters" },
      { name: "Banner Design", desc: "Digital & print banners" },
      { name: "Menu Design", desc: "Restaurant menu creation" },
      { name: "Invitation Card Design", desc: "Event invitations" },
      { name: "Certificate Design", desc: "Award & certificate layouts" },
      { name: "Sticker Design", desc: "Custom sticker artwork" },
      { name: "T-Shirt Design", desc: "Apparel graphic design" },
      { name: "Merchandise Design", desc: "Branded merch creation" },
      { name: "Mug Design", desc: "Custom mug artwork" },
      { name: "Tattoo Design", desc: "Custom tattoo artwork" },
      { name: "Fashion Illustration", desc: "Fashion sketches & art" },
      { name: "Clothing Tech Pack Design", desc: "Garment specification sheets" },
      { name: "Product Label Design", desc: "Label & tag design" },
      { name: "Book Cover Design", desc: "Book & e-book covers" },
      { name: "E-book Design", desc: "Digital book formatting" },
      { name: "Magazine Layout Design", desc: "Editorial layouts" },
      { name: "Canva Design", desc: "Canva template creation" },
      { name: "Infographic Design", desc: "Data visualization graphics" },
      { name: "Resume Writing", desc: "Professional CV creation" },
      { name: "Resume Design", desc: "Visually appealing resumes" },
      { name: "Cover Letter Writing", desc: "Compelling cover letters" },
      { name: "LinkedIn Profile Optimization", desc: "Professional profile setup" },
      { name: "LinkedIn Banner Design", desc: "LinkedIn cover banners" },
      { name: "Twitter Banner Design", desc: "Twitter header graphics" },
      { name: "Facebook Cover Design", desc: "Facebook page covers" },
      { name: "YouTube Thumbnail Design", desc: "Click-worthy thumbnails" },
      { name: "Twitch Overlay Design", desc: "Streamer overlay graphics" },
      { name: "Discord Server Setup", desc: "Community server design" },
      { name: "Mascot Design", desc: "Brand mascot creation" },
      { name: "Character Design", desc: "Original character art" },
      { name: "Comic Illustration", desc: "Comic book artwork" },
      { name: "Storyboarding", desc: "Visual story sequences" },
      { name: "Interior Design", desc: "Space planning & design" },
      { name: "Figma Design", desc: "Figma UI/UX design" },
      { name: "Adobe XD Design", desc: "Adobe XD prototyping" },
      { name: "Sketch App Design", desc: "macOS UI design" },
      { name: "Design System Creation", desc: "Scalable design systems" },
    ],
  },
  {
    id: "marketing",
    title: "Marketing & Growth",
    icon: "Megaphone",
    color: "#a78bfa",
    skills: [
      { name: "SEO", desc: "Search engine optimization" },
      { name: "Social Media Management", desc: "Content & community growth" },
      { name: "Email Marketing", desc: "Campaign management" },
      { name: "PPC Advertising", desc: "Paid media campaigns" },
      { name: "Content Writing", desc: "Blog & article writing" },
      { name: "Copywriting", desc: "Persuasive sales copy" },
      { name: "Market Research", desc: "Industry & market analysis" },
      { name: "Influencer Marketing", desc: "Influencer outreach & campaigns" },
      { name: "TikTok Marketing", desc: "TikTok growth strategies" },
      { name: "TikTok Video Editing", desc: "TikTok content creation" },
      { name: "Instagram Reel Editing", desc: "Instagram reel production" },
      { name: "Instagram Shop Setup", desc: "IG shopping integration" },
      { name: "Facebook Ads Management", desc: "FB advertising campaigns" },
      { name: "Facebook Marketplace Management", desc: "FB marketplace setup" },
      { name: "Google Ads Management", desc: "Google advertising" },
      { name: "Pinterest Marketing", desc: "Pinterest growth strategies" },
      { name: "Reddit Marketing", desc: "Reddit community marketing" },
      { name: "Affiliate Marketing", desc: "Affiliate program management" },
      { name: "Lead Generation", desc: "Prospect acquisition" },
      { name: "Cold Email Outreach", desc: "Email outreach campaigns" },
      { name: "Appointment Setting", desc: "Sales appointment scheduling" },
      { name: "Sales Funnel Creation", desc: "Conversion funnel design" },
      { name: "YouTube Channel Management", desc: "YT channel growth" },
      { name: "Podcast Marketing", desc: "Podcast promotion" },
      { name: "Guest Post Outreach", desc: "Guest blogging campaigns" },
      { name: "SEO Backlink Building", desc: "Link building strategies" },
      { name: "Local SEO Optimization", desc: "Local search optimization" },
      { name: "Technical SEO Audit", desc: "Website SEO health check" },
      { name: "Voice Search Optimization", desc: "Voice SEO strategies" },
      { name: "Retargeting Campaign Management", desc: "Remarketing campaigns" },
      { name: "Conversion Rate Optimization", desc: "CRO & A/B testing" },
      { name: "Funnel Optimization", desc: "Funnel performance tuning" },
      { name: "A/B Testing", desc: "Split test experiments" },
      { name: "Loyalty Program Design", desc: "Customer retention programs" },
      { name: "Referral Program Setup", desc: "Word-of-mouth campaigns" },
      { name: "Influencer Outreach", desc: "Creator partnerships" },
      { name: "PR Campaign Management", desc: "Public relations strategy" },
      { name: "Press Release Writing", desc: "Media announcement drafting" },
      { name: "Sponsorship Proposal Writing", desc: "Sponsor pitch decks" },
      { name: "Media Kit Design", desc: "Creator media packages" },
      { name: "Email Campaign Design", desc: "Visual email templates" },
      { name: "Drip Campaign Setup", desc: "Automated email sequences" },
      { name: "Newsletter Management", desc: "Newsletter creation & distribution" },
      { name: "Newsletter Template Design", desc: "Custom newsletter layouts" },
      { name: "Webinar Funnel Setup", desc: "Webinar marketing funnels" },
    ],
  },
  {
    id: "ai",
    title: "AI & Automation",
    icon: "Brain",
    color: "#f472b6",
    skills: [
      { name: "AI Automation", desc: "Intelligent workflow automation" },
      { name: "AI Chatbot Development", desc: "Conversational AI agents" },
      { name: "Machine Learning", desc: "ML model development" },
      { name: "AI Image Prompt Engineering", desc: "Midjourney & DALL-E prompts" },
      { name: "Midjourney Prompt Writing", desc: "Midjourney art direction" },
      { name: "Stable Diffusion Setup", desc: "SD model configuration" },
      { name: "AI Avatar Creation", desc: "AI-generated avatars" },
      { name: "AI Voice Generation", desc: "Synthetic voice creation" },
      { name: "AI Video Creation", desc: "AI-powered video generation" },
      { name: "AI Content Moderation", desc: "Automated content filtering" },
      { name: "AI Email Writer", desc: "AI email composition" },
      { name: "AI Social Media Automation", desc: "AI-powered social posting" },
      { name: "AI Data Annotation", desc: "Training data labeling" },
      { name: "AI Image Segmentation", desc: "Computer vision labeling" },
      { name: "AI Personal Assistant", desc: "Virtual assistant development" },
      { name: "AI Recommendation Engine", desc: "Personalized recommendations" },
      { name: "AI Fraud Detection", desc: "Fraud prevention systems" },
      { name: "AI Resume Screening", desc: "Automated hiring tools" },
      { name: "AI Customer Support", desc: "AI helpdesk solutions" },
      { name: "Workflow Automation", desc: "Process automation" },
      { name: "Zapier Automation", desc: "Zapier workflow setup" },
      { name: "Notion Workspace Setup", desc: "Notion system design" },
      { name: "Airtable Management", desc: "Airtable database setup" },
      { name: "Excel Automation", desc: "Spreadsheet automation" },
      { name: "Google Sheets Automation", desc: "GSuite automation" },
      { name: "Data Scraping", desc: "Web data extraction" },
      { name: "Web Scraping", desc: "Automated data collection" },
      { name: "Data Mining", desc: "Pattern discovery & extraction" },
      { name: "Machine Learning Models", desc: "Custom ML solutions" },
      { name: "Deep Learning Solutions", desc: "Neural network development" },
      { name: "Computer Vision Projects", desc: "Image & video AI" },
      { name: "NLP Solutions", desc: "Natural language processing" },
      { name: "AI Model Training", desc: "Custom model fine-tuning" },
      { name: "Chatbot Training", desc: "AI bot optimization" },
      { name: "Voice Assistant Development", desc: "Voice-enabled assistants" },
      { name: "AI Agent Development", desc: "Autonomous AI agents" },
      { name: "Prompt Library Creation", desc: "Curated prompt collections" },
      { name: "AI Workflow Design", desc: "AI process architecture" },
      { name: "OCR Automation", desc: "Text recognition automation" },
    ],
  },
  {
    id: "content",
    title: "Content & Writing",
    icon: "PenTool",
    color: "#fbbf24",
    skills: [
      { name: "Content Writing", desc: "Blog & article creation" },
      { name: "Copywriting", desc: "Persuasive sales copy" },
      { name: "Technical Writing", desc: "Documentation & guides" },
      { name: "Translation Services", desc: "Multi-language translation" },
      { name: "Script Writing", desc: "Video & audio scripts" },
      { name: "Subtitle Creation", desc: "Video subtitle generation" },
      { name: "Blog Website Development", desc: "Professional blog platforms" },
      { name: "E-book Design", desc: "Digital book formatting" },
      { name: "Book Formatting", desc: "Print-ready book layout" },
      { name: "Resume Writing", desc: "Professional CV creation" },
      { name: "Cover Letter Writing", desc: "Compelling cover letters" },
      { name: "Grant Writing", desc: "Funding proposal drafting" },
      { name: "Business Proposal Writing", desc: "B2B proposal creation" },
      { name: "Legal Draft Formatting", desc: "Legal document layout" },
      { name: "Press Release Writing", desc: "Media announcement drafting" },
      { name: "SOP Writing", desc: "Standard operating procedures" },
      { name: "User Manual Writing", desc: "Product documentation" },
      { name: "Technical Documentation", desc: "API & system docs" },
      { name: "Knowledge Base Creation", desc: "Help center content" },
      { name: "Wiki Setup", desc: "Internal wiki creation" },
      { name: "Recipe Writing", desc: "Food recipe creation" },
      { name: "Speech Writing", desc: "Presentation scripts" },
      { name: "Speech Coaching", desc: "Public speaking training" },
      { name: "Bookkeeping", desc: "Financial record keeping" },
      { name: "Data Entry", desc: "Information input services" },
      { name: "Handwriting to Text Conversion", desc: "OCR text extraction" },
      { name: "OCR Data Extraction", desc: "Document digitization" },
      { name: "Document Formatting", desc: "Professional document layout" },
      { name: "PDF Conversion", desc: "File format conversion" },
      { name: "Presentation Design", desc: "Slide deck creation" },
      { name: "Pitch Deck Creation", desc: "Investor presentations" },
      { name: "Newsletter Management", desc: "Email newsletter services" },
      { name: "Podcast Intro Script Writing", desc: "Podcast script creation" },
    ],
  },
  {
    id: "media",
    title: "Audio & Video Production",
    icon: "Video",
    color: "#ef4444",
    skills: [
      { name: "Video Editing", desc: "Professional post-production" },
      { name: "Motion Graphics", desc: "Animated visual effects" },
      { name: "Photography", desc: "Product & portrait shots" },
      { name: "Podcast Editing", desc: "Audio post-production" },
      { name: "Voice Over", desc: "Professional narration" },
      { name: "Audio Cleanup", desc: "Noise reduction & mastering" },
      { name: "Music Production", desc: "Original music creation" },
      { name: "Beat Making", desc: "Instrumental production" },
      { name: "Sound Effects Design", desc: "Custom SFX creation" },
      { name: "DJ Mix Creation", desc: "Professional DJ mixes" },
      { name: "Instrumental Production", desc: "Background music tracks" },
      { name: "Piano Composition", desc: "Original piano music" },
      { name: "Guitar Recording", desc: "Professional guitar tracks" },
      { name: "Soundtrack Production", desc: "Film & game scores" },
      { name: "Beat Licensing", desc: "Music licensing services" },
      { name: "Wedding Video Editing", desc: "Wedding highlight reels" },
      { name: "Short Film Editing", desc: "Cinematic film editing" },
      { name: "Documentary Editing", desc: "Documentary post-production" },
      { name: "Cinematic Trailer Creation", desc: "Movie-style trailers" },
      { name: "Intro Animation", desc: "Channel intro videos" },
      { name: "Outro Animation", desc: "Channel outro videos" },
      { name: "Green Screen Editing", desc: "Chroma key compositing" },
      { name: "Screen Recording Editing", desc: "Tutorial video editing" },
      { name: "Gaming Montage Editing", desc: "Gaming highlight reels" },
      { name: "Drone Video Editing", desc: "Aerial footage editing" },
      { name: "Lyric Video Creation", desc: "Animated lyric videos" },
      { name: "Karaoke Video Creation", desc: "Karaoke track videos" },
      { name: "Music Mixing", desc: "Audio track blending" },
      { name: "Audio Mastering", desc: "Professional audio finishing" },
      { name: "Audiobook Recording", desc: "Book narration services" },
      { name: "Voice Cloning", desc: "AI voice replication" },
      { name: "Text-to-Speech", desc: "TTS system development" },
      { name: "Speech-to-Text", desc: "STT transcription systems" },
      { name: "Audio Transcription", desc: "Audio-to-text conversion" },
      { name: "Translation Subtitles", desc: "Multi-language subtitles" },
      { name: "ASMR Audio Editing", desc: "ASMR content production" },
      { name: "Meditation Music Production", desc: "Relaxation audio creation" },
      { name: "Sleep Story Narration", desc: "Sleep story recording" },
      { name: "Soundtrack Production", desc: "Background score creation" },
    ],
  },
  {
    id: "business",
    title: "Business & Consulting",
    icon: "Briefcase",
    color: "#34d399",
    skills: [
      { name: "Business Consulting", desc: "Strategy & growth planning" },
      { name: "CRM Management", desc: "Customer relationship tools" },
      { name: "Financial Analysis", desc: "Business intelligence" },
      { name: "Lead Generation", desc: "Prospect acquisition" },
      { name: "Project Management", desc: "Project coordination" },
      { name: "Virtual Assistance", desc: "Administrative support" },
      { name: "Event Planning", desc: "Event coordination" },
      { name: "Business Card Design", desc: "Professional card design" },
      { name: "Sales Page Copywriting", desc: "High-converting sales copy" },
      { name: "Business Proposal Writing", desc: "B2B proposal creation" },
      { name: "Startup Consulting", desc: "Startup growth strategy" },
      { name: "Pitch Coaching", desc: "Investor pitch preparation" },
      { name: "Investor Deck Design", desc: "Funding presentations" },
      { name: "Recruitment Assistance", desc: "Hiring & talent sourcing" },
      { name: "HR Consulting", desc: "Human resources strategy" },
      { name: "Interview Coaching", desc: "Interview preparation" },
      { name: "Career Counseling", desc: "Career path guidance" },
      { name: "Mock Interviews", desc: "Practice interview sessions" },
      { name: "Internship Assistance", desc: "Internship placement help" },
      { name: "Tax Preparation Support", desc: "Tax filing assistance" },
      { name: "Accounting Assistance", desc: "Bookkeeping services" },
      { name: "Financial Planning", desc: "Personal finance strategy" },
      { name: "Budget Tracking Spreadsheet", desc: "Financial tracking tools" },
      { name: "Expense Categorization Automation", desc: "Expense management" },
      { name: "Invoice Design", desc: "Professional invoice templates" },
      { name: "Contract Formatting", desc: "Legal document layout" },
      { name: "Legal Research Assistance", desc: "Legal information research" },
      { name: "Compliance Documentation", desc: "Regulatory compliance docs" },
      { name: "Policy Draft Formatting", desc: "Policy document creation" },
      { name: "Business Registration Assistance", desc: "Company formation help" },
      { name: "Startup Naming Consultation", desc: "Brand naming strategy" },
      { name: "Domain Name Research", desc: "Domain availability search" },
      { name: "Brand Slogan Creation", desc: "Catchphrase development" },
      { name: "Mission Statement Writing", desc: "Company mission drafting" },
      { name: "Rebranding Consultation", desc: "Brand refresh strategy" },
      { name: "Brand Voice Development", desc: "Brand tone & personality" },
      { name: "Luxury Brand Identity", desc: "Premium brand design" },
      { name: "Talent Sourcing", desc: "Candidate identification" },
      { name: "Real Estate Listing Management", desc: "Property listing services" },
      { name: "Property Research", desc: "Market property analysis" },
      { name: "Airbnb Management", desc: "Short-term rental management" },
      { name: "Travel Planning", desc: "Travel itinerary design" },
      { name: "Visa Consultation", desc: "Immigration guidance" },
      { name: "Subscription Service Setup", desc: "Recurring revenue setup" },
      { name: "Loyalty Rewards System", desc: "Customer loyalty programs" },
    ],
  },
  {
    id: "infra",
    title: "Infrastructure & DevOps",
    icon: "Server",
    color: "#f97316",
    skills: [
      { name: "Cloud Computing", desc: "AWS, Azure, GCP services" },
      { name: "Cybersecurity", desc: "Security audits & pentesting" },
      { name: "DevOps", desc: "CI/CD & infrastructure" },
      { name: "Database Management", desc: "SQL & NoSQL solutions" },
      { name: "Server Management", desc: "Linux & Windows servers" },
      { name: "Website Maintenance", desc: "Ongoing support & updates" },
      { name: "Website Speed Optimization", desc: "Performance tuning" },
      { name: "Bug Fixing", desc: "Issue resolution" },
      { name: "Software Testing", desc: "QA & test automation" },
      { name: "QA Automation", desc: "Automated quality assurance" },
      { name: "Ethical Hacking", desc: "Authorized security testing" },
      { name: "Penetration Testing", desc: "Vulnerability assessment" },
      { name: "Network Setup", desc: "Network infrastructure" },
      { name: "IT Consulting", desc: "Technology advisory" },
      { name: "SaaS Development", desc: "Software-as-a-service" },
      { name: "ERP System Setup", desc: "Enterprise resource planning" },
      { name: "POS System Development", desc: "Point-of-sale systems" },
      { name: "Inventory Management System", desc: "Stock control systems" },
      { name: "HR Software Development", desc: "Human resources systems" },
      { name: "Payroll System Setup", desc: "Employee payment systems" },
      { name: "Payment Gateway Integration", desc: "Payment processing" },
      { name: "Stripe Integration", desc: "Stripe payment setup" },
      { name: "PayPal Integration", desc: "PayPal payment setup" },
      { name: "MongoDB Setup", desc: "NoSQL database configuration" },
      { name: "MySQL Optimization", desc: "Database performance tuning" },
      { name: "Firebase Integration", desc: "Google Firebase setup" },
      { name: "Docker Containerization", desc: "Container deployment" },
      { name: "Kubernetes Deployment", desc: "K8s orchestration" },
      { name: "AWS Cloud Setup", desc: "Amazon Web Services" },
      { name: "Google Cloud Setup", desc: "GCP configuration" },
      { name: "Azure Cloud Setup", desc: "Microsoft Azure services" },
      { name: "VPS Configuration", desc: "Virtual private server setup" },
      { name: "CDN Setup", desc: "Content delivery network" },
      { name: "SSL Certificate Installation", desc: "HTTPS security setup" },
      { name: "DNS Management", desc: "Domain name system config" },
      { name: "Website Migration", desc: "Site transfer services" },
      { name: "Backup System Setup", desc: "Automated backups" },
      { name: "Disaster Recovery Planning", desc: "Business continuity" },
      { name: "Email Server Setup", desc: "Mail server configuration" },
      { name: "SMTP Configuration", desc: "Email delivery setup" },
      { name: "Malware Removal", desc: "Virus & malware cleanup" },
      { name: "Website Security Audit", desc: "Security assessment" },
      { name: "Anti-Spam Protection", desc: "Spam filtering setup" },
      { name: "Firewall Configuration", desc: "Network security rules" },
      { name: "CRM Integration", desc: "CRM system connections" },
      { name: "CRM Customization", desc: "Tailored CRM solutions" },
      { name: "CRM Data Cleanup", desc: "Database hygiene" },
      { name: "Linux Administration", desc: "Linux server management" },
      { name: "Server Deployment", desc: "Production deployment" },
      { name: "GitHub Repository Management", desc: "Git workflow setup" },
      { name: "GitLab CI/CD Setup", desc: "Continuous integration" },
    ],
  },
  {
    id: "data",
    title: "Data & Analytics",
    icon: "BarChart3",
    color: "#06b6d4",
    skills: [
      { name: "Data Analysis", desc: "Business intelligence" },
      { name: "Data Visualization", desc: "Charts & dashboards" },
      { name: "Data Entry", desc: "Information input services" },
      { name: "Data Scraping", desc: "Web data extraction" },
      { name: "Data Mining", desc: "Pattern discovery" },
      { name: "Spreadsheet Cleanup", desc: "Data hygiene services" },
      { name: "CSV Data Cleanup", desc: "CSV file optimization" },
      { name: "Data Conversion", desc: "Format transformation" },
      { name: "Power BI Dashboard", desc: "Microsoft BI dashboards" },
      { name: "Tableau Dashboard", desc: "Tableau visualizations" },
      { name: "Excel Dashboard Design", desc: "Advanced Excel dashboards" },
      { name: "KPI Reporting", desc: "Key performance indicators" },
      { name: "Business Intelligence", desc: "BI strategy & implementation" },
      { name: "Predictive Analytics", desc: "Future trend forecasting" },
      { name: "Statistical Analysis", desc: "Statistical modeling" },
      { name: "Survey Data Analysis", desc: "Survey result processing" },
      { name: "Behavioral Data Analysis", desc: "User behavior insights" },
      { name: "Churn Prediction Modeling", desc: "Retention analysis" },
      { name: "Customer Segmentation", desc: "Audience grouping" },
      { name: "Lead Scoring Models", desc: "Lead quality scoring" },
      { name: "Business Forecasting", desc: "Revenue & growth prediction" },
      { name: "Inventory Forecast Analytics", desc: "Stock prediction" },
      { name: "Sales Reporting Automation", desc: "Automated sales reports" },
      { name: "Financial Dashboard Creation", desc: "Finance dashboards" },
      { name: "Budget Tracking", desc: "Budget monitoring tools" },
      { name: "Expense Tracking", desc: "Expense management" },
      { name: "Crypto Portfolio Tracker", desc: "Cryptocurrency tracking" },
      { name: "Investment Portfolio Dashboard", desc: "Investment analytics" },
      { name: "Real-Time Stock Alerts", desc: "Stock price notifications" },
      { name: "Forex Trading Journal", desc: "FX trade tracking" },
      { name: "Google Analytics Configuration", desc: "GA4 setup & reporting" },
      { name: "Tag Manager Setup", desc: "GTM implementation" },
      { name: "Conversion Pixel Setup", desc: "Tracking pixel configuration" },
      { name: "Heatmap Tracking Integration", desc: "User behavior heatmaps" },
      { name: "Funnel Drop-Off Analysis", desc: "Conversion path analysis" },
      { name: "Market Trend Analysis", desc: "Industry trend research" },
      { name: "Competitor Analysis", desc: "Competitive intelligence" },
      { name: "Consumer Research", desc: "Consumer insights" },
      { name: "Academic Research", desc: "Research assistance" },
      { name: "Survey Creation", desc: "Custom survey design" },
      { name: "Quiz Creation", desc: "Interactive quiz development" },
      { name: "Form Building", desc: "Custom form creation" },
    ],
  },
  {
    id: "emerging",
    title: "Emerging Tech & Innovation",
    icon: "Sparkles",
    color: "#ec4899",
    skills: [
      { name: "Blockchain Development", desc: "Smart contracts & dApps" },
      { name: "Smart Contract Development", desc: "Solidity programming" },
      { name: "Solidity Programming", desc: "Ethereum development" },
      { name: "Crypto Wallet Integration", desc: "Wallet connectivity" },
      { name: "NFT Marketplace Development", desc: "NFT platform creation" },
      { name: "NFT Art Creation", desc: "Digital collectible art" },
      { name: "NFT Smart Contract Auditing", desc: "NFT contract security" },
      { name: "Crypto Tokenomics Planning", desc: "Token economics design" },
      { name: "DAO Setup", desc: "Decentralized organizations" },
      { name: "DAO Governance Design", desc: "Voting & governance" },
      { name: "Blockchain Whitepaper Writing", desc: "Technical whitepapers" },
      { name: "ICO Landing Page Design", desc: "Token sale pages" },
      { name: "Web3 Community Moderation", desc: "Web3 community mgmt" },
      { name: "Wallet Security Consultation", desc: "Crypto wallet safety" },
      { name: "Decentralized App UI Design", desc: "dApp interfaces" },
      { name: "Metaverse Storefront Design", desc: "Virtual shop creation" },
      { name: "Metaverse Environment Design", desc: "Virtual world building" },
      { name: "Virtual Reality Experiences", desc: "VR content creation" },
      { name: "VR Event Production", desc: "Virtual event experiences" },
      { name: "360 Video Editing", desc: "Immersive video content" },
      { name: "Immersive Audio Production", desc: "Spatial audio creation" },
      { name: "AR Filter Creation", desc: "Augmented reality filters" },
      { name: "AR Learning Experience", desc: "Educational AR content" },
      { name: "IoT Development", desc: "Internet of Things solutions" },
      { name: "Smart Home Automation", desc: "Connected home systems" },
      { name: "Home Automation Setup", desc: "Smart device integration" },
      { name: "Smart Security System", desc: "IoT security solutions" },
      { name: "Wearable Tech Development", desc: "Smart device apps" },
      { name: "Fitness Wearable Integration", desc: "Health device connectivity" },
      { name: "Drone Programming", desc: "UAV software development" },
      { name: "Drone Mapping", desc: "Aerial mapping services" },
      { name: "Drone Video Editing", desc: "Aerial footage editing" },
      { name: "Robotics Programming", desc: "Robot software development" },
      { name: "Embedded Systems Programming", desc: "Microcontroller coding" },
      { name: "Arduino Projects", desc: "Arduino prototyping" },
      { name: "Raspberry Pi Projects", desc: "RPi development" },
      { name: "Biometric System Setup", desc: "Biometric authentication" },
      { name: "Facial Recognition Integration", desc: "Face recognition systems" },
      { name: "Smart Mirror Interface Design", desc: "Mirror UI development" },
      { name: "Smart Car Dashboard UI", desc: "Automotive interfaces" },
      { name: "EV Charging App Development", desc: "Electric vehicle apps" },
      { name: "EV Battery Health Tracker", desc: "Battery monitoring" },
      { name: "Solar Energy Calculator", desc: "Solar power analytics" },
      { name: "Smart Home Energy Dashboard", desc: "Energy monitoring UI" },
      { name: "Environmental Data Mapping", desc: "Eco data visualization" },
      { name: "Air Quality Monitoring UI", desc: "Pollution tracking" },
      { name: "Water Usage Analytics", desc: "Water consumption tracking" },
      { name: "Carbon Footprint Tracking", desc: "Emission monitoring" },
      { name: "Renewable Energy Consultation", desc: "Clean energy advisory" },
      { name: "Sustainability Consulting", desc: "Green business strategy" },
      { name: "Recycling Awareness Campaign", desc: "Eco campaigns" },
    ],
  },
];

// Flat list of all service names for dropdowns
export const allServiceNames = serviceCategories.flatMap(c => c.skills.map(s => s.name));

// Featured/popular services for Home page (24 items)
export const featuredServices = [
  { icon: "Code2", label: "Web Development", desc: "Custom websites & web apps" },
  { icon: "Palette", label: "Graphic Design", desc: "Visual identity & branding" },
  { icon: "Smartphone", label: "App Development", desc: "iOS & Android apps" },
  { icon: "Video", label: "Video Editing", desc: "Professional post-production" },
  { icon: "Brain", label: "AI Automation", desc: "Intelligent workflows" },
  { icon: "Search", label: "SEO", desc: "Search engine optimization" },
  { icon: "Megaphone", label: "Digital Marketing", desc: "Growth & campaigns" },
  { icon: "Figma", label: "UI/UX Design", desc: "User interface design" },
  { icon: "Bot", label: "AI Chatbots", desc: "Conversational AI" },
  { icon: "PenTool", label: "Content Writing", desc: "Blog & copywriting" },
  { icon: "Blocks", label: "Blockchain", desc: "Smart contracts & dApps" },
  { icon: "Cloud", label: "Cloud Computing", desc: "AWS, Azure, GCP" },
  { icon: "Lock", label: "Cybersecurity", desc: "Security audits" },
  { icon: "Database", label: "Data Analysis", desc: "Business intelligence" },
  { icon: "Gamepad2", label: "Game Development", desc: "Unity & Unreal" },
  { icon: "Camera", label: "Photography", desc: "Product & portrait" },
  { icon: "Mic", label: "Voice Over", desc: "Professional narration" },
  { icon: "ShoppingCart", label: "E-commerce", desc: "Online store dev" },
  { icon: "Sparkles", label: "NFT Design", desc: "Digital collectibles" },
  { icon: "BarChart3", label: "Market Research", desc: "Industry analysis" },
  { icon: "TrendingUp", label: "PPC Ads", desc: "Paid media campaigns" },
  { icon: "Globe", label: "Social Media", desc: "Community management" },
  { icon: "Mail", label: "Email Marketing", desc: "Campaign automation" },
  { icon: "Zap", label: "Automation", desc: "Workflow automation" },
];

// Stats
export const serviceStats = {
  categories: serviceCategories.length,
  total: allServiceNames.length,
};
